# Generated by Django 4.2.17 on 2024-12-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='date_join',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(to='mrp_api.roles'),
        ),
    ]
