# Generated by Django 4.2.17 on 2024-12-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_api', '0002_modules_roles_employee_date_join_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(to='mrp_api.departments'),
        ),
    ]
