# Generated by Django 4.2.17 on 2024-12-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_api', '0005_modulepermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='locked',
            field=models.IntegerField(default=0),
        ),
    ]
