# Generated by Django 4.2.17 on 2025-01-02 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_api', '0006_employee_attempts_employee_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submodules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submodule', models.CharField(max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_api.modules')),
            ],
        ),
    ]
