# Generated by Django 4.2.17 on 2025-01-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_api', '0007_submodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='slug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submodules',
            name='slug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
