# Generated by Django 4.2.17 on 2025-01-03 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_api', '0008_modules_icon_modules_slug_submodules_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='mrp_api.employee'),
        ),
    ]
