# Generated by Django 4.2.17 on 2025-01-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_api', '0009_employee_superior'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
