# Generated by Django 4.2.17 on 2025-01-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_api', '0010_employee_cellphone_number_employee_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email_address',
        ),
    ]
