# Generated by Django 4.2.17 on 2025-01-10 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrp_api', '0011_remove_employee_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='municipality',
        ),
        migrations.AddField(
            model_name='employee',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='module_permissions',
            field=models.ManyToManyField(blank=True, null=True, to='mrp_api.modulepermissions'),
        ),
        migrations.AddField(
            model_name='employee',
            name='modules',
            field=models.ManyToManyField(to='mrp_api.modules'),
        ),
        migrations.AddField(
            model_name='employee',
            name='submodules',
            field=models.ManyToManyField(blank=True, null=True, to='mrp_api.submodules'),
        ),
        migrations.AddField(
            model_name='modules',
            name='components',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='path',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='modules',
            field=models.ManyToManyField(blank=True, to='mrp_api.modules'),
        ),
        migrations.AddField(
            model_name='roles',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='mrp_api.modulepermissions'),
        ),
        migrations.AddField(
            model_name='roles',
            name='submodules',
            field=models.ManyToManyField(blank=True, to='mrp_api.submodules'),
        ),
        migrations.AddField(
            model_name='submodules',
            name='components',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='area',
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp_api.area')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, to='mrp_api.area'),
        ),
    ]
