# Generated by Django 4.2.17 on 2025-01-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_api', '0012_remove_area_municipality_employee_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='mrp_api.roles'),
        ),
    ]
