# Generated by Django 4.2.17 on 2025-01-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_api', '0013_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='icon',
            field=models.CharField(blank=True, choices=[('#home', '#home'), ('#speedometer2', '#speedometer2'), ('#table', '#table'), ('#grid', '#grid')], default='#table', max_length=100, null=True),
        ),
    ]
