# Generated by Django 4.2.17 on 2025-01-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp_api', '0014_alter_modules_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, to='mrp_api.area'),
        ),
    ]
